project:
  type: website
  output-dir: docs

website:
  title: "Tra Tran"
  navbar:
    left:
      - href: home/index.qmd
        text: Home
      - href: about/index.qmd
        text: About
      - href: project/index.qmd
        text: Project
      - href: blog/index.qmd
        text: Blog
    right:
      - href: https://github.com/tranlevantra/personal_website
        icon: github
  
  page-footer: 
    center: This website is built with [Quarto](https://quarto.org/docs/websites/) and hosted on [Github Pages](https://pages.github.com)

format:
  html:
    link-external-newwindow: true
    link-external-icon: true
    theme: cosmo
    css: styles.css

editor: visual

