---
title: "Greater Melbourne Distribution Center Landscape"
format: html
---

## Background

This project aims to analyze the distribution center landscape in the Greater Melbourne area and point out changes in the landscape post-COVID-19. The analysis will focus on the following aspects:

1.  Distribution center locations
2.  Distribution center sizes

## Population Density
Population density is a key factor in determining the location of distribution centers.

<iframe src="fig/populationDensity_Vic.html" width="100%" height="600" style="border:none;"></iframe>

## Distribution Center Locations

Distribution centers are typically located in areas with high population density and good access to transportation networks. The following map shows the locations of distribution centers in the Greater Melbourne area.

<iframe src="fig/FullfillmentCenter_GreaterMelbourne.html" width="100%" height="600" style="border:none;"></iframe>




## Findings

-   More inhouse Fullfillment Centers as businesses are moving towards securing their own supply chains to deal with disruptions and uncertainties.

- The warehouse zone is get crowded with more and more distribution centers. In the near future, unoccupied land across the Sunburry line will become hotspot for new warehouses thanks to its accessibility to the metropolitan zone.

